/**
 * Minimal HTML sanitizer for notification messages.
 * Content is generated by our own server code (buildAssignmentMessage),
 * but this provides defense-in-depth against any unexpected injection.
 */

const DANGEROUS_TAGS = /(<script[\s\S]*?<\/script>|<iframe[\s\S]*?<\/iframe>|<object[\s\S]*?<\/object>|<embed[^>]*>|<form[\s\S]*?<\/form>)/gi;
const DANGEROUS_ATTRS = /\s(on\w+|formaction|srcdoc|xlink:href)\s*=\s*["'][^"']*["']/gi;
const JAVASCRIPT_HREF = /href\s*=\s*["']\s*javascript:[^"']*["']/gi;

/**
 * Works on both server and client. Strips script tags, event handlers,
 * and javascript: hrefs. Safe for rendering notification messages.
 */
export function sanitizeHtml(html: string): string {
  // Reemplaza <script> por <template> para evitar warnings de React/Next.js
  let sanitized = html
    .replace(/<script/gi, '<template')
    .replace(/<\/script/gi, '</template')
    .replace(DANGEROUS_TAGS, "")
    .replace(DANGEROUS_ATTRS, "")
    .replace(JAVASCRIPT_HREF, 'href="#"');
  return sanitized;
}
